"""Tests for human-style manufacturer inquiry drafts."""

import email_service


BLOCKED_PHRASES = [
    "i am an ai",
    "generated by ai",
    "our system detected",
    "according to our algorithm",
    "halal certification is required from you",
    "system-generated",
    "bot",
]


def test_manufacturer_email_draft_is_short_and_natural(monkeypatch) -> None:
    monkeypatch.setattr(email_service.config, "SENDER_DISPLAY_NAME", "Ali")
    monkeypatch.setattr(email_service.config, "GMAIL_SENDER_EMAIL", "halalcheckde@gmail.com")
    monkeypatch.setattr(email_service.config, "FROM_EMAIL", "user@example.com")
    monkeypatch.setattr(email_service.config, "REPLY_TO_EMAIL", "user-reply@example.com")
    product = {
        "name": "Chocolate Biscuit",
        "brand": "BakeHouse",
        "barcode": "4000000000034",
    }
    issue = {"ingredient": "E471"}

    draft = email_service.generate_manufacturer_email_draft(product, issue)
    body_lower = draft["body"].lower()

    assert draft["subject"] == "Question about ingredient source in Chocolate Biscuit"
    assert len(draft["subject"]) < 80
    assert "Product: Chocolate Biscuit" in draft["body"]
    assert "Brand: BakeHouse" in draft["body"]
    assert "Barcode: 4000000000034" in draft["body"]
    assert "Ingredient: E471" in draft["body"]
    assert "plant-based, animal-based, microbial, synthetic, or alcohol-derived" in draft["body"]
    assert draft["body"].endswith("Kind regards,\nAli")
    assert draft["sender"] == "Ali <halalcheckde@gmail.com>"
    assert draft["reply_to"] == "halalcheckde@gmail.com"
    assert not any(phrase in body_lower for phrase in BLOCKED_PHRASES)


def test_manufacturer_email_draft_omits_missing_barcode(monkeypatch) -> None:
    monkeypatch.setattr(email_service.config, "SENDER_DISPLAY_NAME", "")
    product = {"name": "Vanilla Dessert", "brand": "", "barcode": ""}
    issue = {"ingredient": "Aroma"}

    draft = email_service.generate_manufacturer_email_draft(product, issue)

    assert "Barcode:" not in draft["body"]
    assert "Ingredient: Aroma" in draft["body"]
    assert draft["body"].endswith("Kind regards")


def test_manufacturer_email_uses_barcode_label_when_name_missing(monkeypatch) -> None:
    monkeypatch.setattr(email_service.config, "SENDER_DISPLAY_NAME", "Ali")
    product = {"name": "", "brand": "", "barcode": "12345"}
    issue = {"ingredient": "flavouring"}

    draft = email_service.generate_manufacturer_email_draft(product, issue)

    assert draft["subject"] == "Question about ingredient source in your product with barcode 12345"
    assert "Product: your product with barcode 12345" in draft["body"]
    assert "Barcode: 12345" in draft["body"]
